<?php

namespace App\Services\Instagram;

use App\Models\InstagramSetting;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

/**
 * The OAuth dance, as Instagram defines it.
 *
 * Meaning lives here; the HTTP lives in InstagramGraph. Nothing in this class
 * touches the database -- InstagramConnector does that -- so the flow can be
 * followed end to end without also reading a schema.
 */
class InstagramOAuth
{
    /**
     * What we ask the client to grant.
     *
     * `instagram_business_manage_insights` is not used until Phase 3, and is
     * requested now on purpose: adding a scope later means walking every
     * connected client back through a consent screen, which is a conversation
     * nobody wants to have twice.
     *
     * `instagram_business_basic` is mandatory -- Instagram refuses the
     * authorize request without it.
     *
     * @var list<string>
     */
    public const SCOPES = [
        'instagram_business_basic',
        'instagram_business_manage_insights',
    ];

    /** How long a token lives when Instagram does not say. ~60 days. */
    private const DEFAULT_TOKEN_LIFETIME_SECONDS = 5_184_000;

    public function __construct(
        private readonly InstagramGraph $graph,
        private readonly InstagramSetting $settings,
    ) {}

    public static function make(): self
    {
        return new self(new InstagramGraph, InstagramSetting::current());
    }

    /** A fresh, unguessable state value for one authorization attempt. */
    public static function freshState(): string
    {
        return Str::random(40);
    }

    /**
     * Where to send the client to authorise.
     *
     * `state` is generated by the caller and stashed in the session, not here:
     * this class must not know about sessions, and the value has to be written
     * somewhere the callback can compare it against.
     */
    public function authorizationUrl(string $state): string
    {
        if (! $this->settings->isConfigured()) {
            throw new InstagramException(
                'Instagram is not configured yet. Add the app ID and secret under Setup → Instagram.'
            );
        }

        return InstagramGraph::AUTHORIZE_URL.'?'.http_build_query([
            /*
             * force_reauth makes Instagram ask for credentials even when the
             * browser already has a session. That matters here more than it
             * would elsewhere: a staff member connecting a CLIENT's account is
             * usually signed in to the studio's own Instagram, and without
             * this the consent screen would quietly offer that account instead
             * -- connecting the wrong Instagram to the right client, with
             * nothing on screen saying so.
             */
            'force_reauth' => 'true',
            'client_id' => $this->settings->app_id,
            'redirect_uri' => $this->settings->callbackUrl(),
            'response_type' => 'code',
            'scope' => implode(',', self::SCOPES),
            'state' => $state,
        ]);
    }

    /**
     * Code → a long-lived token, in one step from the caller's point of view.
     *
     * The two-hop exchange is an Instagram implementation detail: a short-lived
     * token is useless to store, so no caller is ever handed one.
     *
     * @return array{token: string, expires_at: Carbon, user_id: string|null, permissions: list<string>}
     */
    public function exchangeCode(string $code): array
    {
        $short = $this->graph->exchangeCode(
            (string) $this->settings->app_id,
            (string) $this->settings->app_secret,
            $this->settings->callbackUrl(),
            $code,
        );

        $shortToken = $short['access_token'] ?? null;

        if (! is_string($shortToken) || $shortToken === '') {
            throw new InstagramException('Instagram did not return an access token for that code.');
        }

        $long = $this->graph->exchangeForLongLivedToken((string) $this->settings->app_secret, $shortToken);

        $token = $long['access_token'] ?? $shortToken;
        $expires = (int) ($long['expires_in'] ?? self::DEFAULT_TOKEN_LIFETIME_SECONDS);

        return [
            'token' => $token,
            'expires_at' => now()->addSeconds($expires),
            // Instagram returns user_id on the short-lived response only.
            'user_id' => isset($short['user_id']) ? (string) $short['user_id'] : null,
            // What was actually granted, which is not always what was asked --
            // a client can untick a permission on the consent screen.
            'permissions' => $this->grantedScopes($short),
        ];
    }

    /**
     * The connected account's own details.
     *
     * `user_id` rather than `id`: on this API they are different fields, and
     * `id` is the app-scoped one that changes between apps -- storing it would
     * mean the same Instagram account looked like a new one if the studio ever
     * moved to a different Meta app.
     *
     * @return array<string, mixed>
     */
    public function getAccount(string $accessToken): array
    {
        return $this->graph->get('me', $accessToken, [
            'fields' => 'user_id,username,account_type,followers_count,media_count,profile_picture_url',
        ]);
    }

    /**
     * @param  array<string, mixed>  $response
     * @return list<string>
     */
    private function grantedScopes(array $response): array
    {
        $permissions = $response['permissions'] ?? null;

        if (is_array($permissions)) {
            return array_values(array_map('strval', $permissions));
        }

        // Older responses hand back a comma-separated string.
        if (is_string($permissions) && $permissions !== '') {
            return array_values(array_filter(array_map('trim', explode(',', $permissions))));
        }

        return self::SCOPES;
    }
}
